export const REQUEST_CATS = "REQUEST CATS";
export const REQUEST_CATS_SUCCESS = "REQUEST CATS SUCCESS";
export const REQUEST_CATS_FAILED = "REQUEST CATS FAILED";

export const REMOVE_CAT = 'REMOVE_CAT';